apiVersion: v1
kind: Service
metadata:
  name: banking-system-service
  namespace: banking-system
  labels:
    app.kubernetes.io/name: banking-system
    app.kubernetes.io/component: service
spec:
  type: ClusterIP
  selector:
    app: banking-system
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
